/* eslint-disable no-useless-escape */

export const phpLanguageConfig: any = {
  wordPattern: /(-?\d*\.\d\w*)|([^\`\~\!\@\#\%\^\&\*\(\)\-\=\+\[\{\]\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g,
  comments: {
    lineComment: '//',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}', notIn: ['string'] },
    { open: '[', close: ']', notIn: ['string'] },
    { open: '(', close: ')', notIn: ['string'] },
    { open: '"', close: '"', notIn: ['string'] },
    { open: "'", close: "'", notIn: ['string', 'comment'] },
  ],
  folding: {
    markers: {
      start: new RegExp('^\\s*(#|//)region\\b'),
      end: new RegExp('^\\s*(#|//)endregion\\b'),
    },
  },
};

export const phpMonarchDefinition: any = {
  defaultToken: '',
  tokenPostfix: '',

  tokenizer: {
    root: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.root' }],
      [/<!DOCTYPE/, 'metatag.html', '@doctype'],
      [/<!--/, 'comment.html', '@comment'],
      [/(<)(\w+)(\/>)/, ['delimiter.html', 'tag.html', 'delimiter.html']],
      [/(<)(script)/, ['delimiter.html', { token: 'tag.html', next: '@script' }]],
      [/(<)(style)/, ['delimiter.html', { token: 'tag.html', next: '@style' }]],
      [/(<)([:\w]+)/, ['delimiter.html', { token: 'tag.html', next: '@otherTag' }]],
      [/(<\/)(\w+)/, ['delimiter.html', { token: 'tag.html', next: '@otherTag' }]],
      [/</, 'delimiter.html'],
      [/[^<]+/],
    ],
    doctype: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.comment' }],
      [/[^>]+/, 'metatag.content.html'],
      [/>/, 'metatag.html', '@pop'],
    ],
    comment: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.comment' }],
      [/-->/, 'comment.html', '@pop'],
      [/[^-]+/, 'comment.content.html'],
      [/./, 'comment.content.html'],
    ],
    otherTag: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.otherTag' }],
      [/\/?>/, 'delimiter.html', '@pop'],
      [/"([^"]*)"/, 'attribute.value'],
      [/'([^']*)'/, 'attribute.value'],
      [/[\w\-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/[ \t\r\n]+/],
    ],
    script: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.script' }],
      [/type/, 'attribute.name', '@scriptAfterType'],
      [/"([^"]*)"/, 'attribute.value'],
      [/'([^']*)'/, 'attribute.value'],
      [/[\w\-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@scriptEmbedded.text/javascript',
          nextEmbedded: 'text/javascript',
        },
      ],
      [/[ \t\r\n]+/],
      [
        /(<\/)(script\s*)(>)/,
        ['delimiter.html', 'tag.html', { token: 'delimiter.html', next: '@pop' }],
      ],
    ],
    scriptAfterType: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.scriptAfterType',
        },
      ],
      [/=/, 'delimiter', '@scriptAfterTypeEquals'],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@scriptEmbedded.text/javascript',
          nextEmbedded: 'text/javascript',
        },
      ],
      [/[ \t\r\n]+/],
      [/<\/script\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    scriptAfterTypeEquals: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.scriptAfterTypeEquals',
        },
      ],
      [
        /"([^"]*)"/,
        {
          token: 'attribute.value',
          switchTo: '@scriptWithCustomType.$1',
        },
      ],
      [
        /'([^']*)'/,
        {
          token: 'attribute.value',
          switchTo: '@scriptWithCustomType.$1',
        },
      ],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@scriptEmbedded.text/javascript',
          nextEmbedded: 'text/javascript',
        },
      ],
      [/[ \t\r\n]+/],
      [/<\/script\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    scriptWithCustomType: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.scriptWithCustomType.$S2',
        },
      ],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@scriptEmbedded.$S2',
          nextEmbedded: '$S2',
        },
      ],
      [/"([^"]*)"/, 'attribute.value'],
      [/'([^']*)'/, 'attribute.value'],
      [/[\w\-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/[ \t\r\n]+/],
      [/<\/script\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    scriptEmbedded: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInEmbeddedState.scriptEmbedded.$S2',
          nextEmbedded: '@pop',
        },
      ],
      [/<\/script/, { token: '@rematch', next: '@pop', nextEmbedded: '@pop' }],
    ],
    style: [
      [/<\?((php)|=)?/, { token: '@rematch', switchTo: '@phpInSimpleState.style' }],
      [/type/, 'attribute.name', '@styleAfterType'],
      [/"([^"]*)"/, 'attribute.value'],
      [/'([^']*)'/, 'attribute.value'],
      [/[\w\-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@styleEmbedded.text/css',
          nextEmbedded: 'text/css',
        },
      ],
      [/[ \t\r\n]+/],
      [
        /(<\/)(style\s*)(>)/,
        ['delimiter.html', 'tag.html', { token: 'delimiter.html', next: '@pop' }],
      ],
    ],
    styleAfterType: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.styleAfterType',
        },
      ],
      [/=/, 'delimiter', '@styleAfterTypeEquals'],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@styleEmbedded.text/css',
          nextEmbedded: 'text/css',
        },
      ],
      [/[ \t\r\n]+/],
      [/<\/style\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    styleAfterTypeEquals: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.styleAfterTypeEquals',
        },
      ],
      [
        /"([^"]*)"/,
        {
          token: 'attribute.value',
          switchTo: '@styleWithCustomType.$1',
        },
      ],
      [
        /'([^']*)'/,
        {
          token: 'attribute.value',
          switchTo: '@styleWithCustomType.$1',
        },
      ],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@styleEmbedded.text/css',
          nextEmbedded: 'text/css',
        },
      ],
      [/[ \t\r\n]+/],
      [/<\/style\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    styleWithCustomType: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInSimpleState.styleWithCustomType.$S2',
        },
      ],
      [
        />/,
        {
          token: 'delimiter.html',
          next: '@styleEmbedded.$S2',
          nextEmbedded: '$S2',
        },
      ],
      [/"([^"]*)"/, 'attribute.value'],
      [/'([^']*)'/, 'attribute.value'],
      [/[\w\-]+/, 'attribute.name'],
      [/=/, 'delimiter'],
      [/[ \t\r\n]+/],
      [/<\/style\s*>/, { token: '@rematch', next: '@pop' }],
    ],
    styleEmbedded: [
      [
        /<\?((php)|=)?/,
        {
          token: '@rematch',
          switchTo: '@phpInEmbeddedState.styleEmbedded.$S2',
          nextEmbedded: '@pop',
        },
      ],
      [/<\/style/, { token: '@rematch', next: '@pop', nextEmbedded: '@pop' }],
    ],
    phpInSimpleState: [
      [/<\?((php)|=)?/, 'metatag.php'],
      [/\?>/, { token: 'metatag.php', switchTo: '@$S2.$S3' }],
      { include: 'phpRoot' },
    ],
    phpInEmbeddedState: [
      [/<\?((php)|=)?/, 'metatag.php'],
      [
        /\?>/,
        {
          token: 'metatag.php',
          switchTo: '@$S2.$S3',
          nextEmbedded: '$S3',
        },
      ],
      { include: 'phpRoot' },
    ],
    phpRoot: [
      // Function declaration: function myFunc(...)
      [/(function)(\s+)([a-zA-Z_]\w*)/, ['keyword.php', '', 'support.function.php']],
      // Function call identification (e.g. var_dump(...), print_r(...), custom_func(...))
      [/[a-zA-Z_]\w*(?=\s*\()/, 'support.function.php'],
      // Uppercase constant identifiers (e.g. NAME, PI, SITE_URL)
      [/[A-Z_][A-Z0-9_]{1,}/, 'constant.php'],
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            '@phpConstants': { token: 'constant.php' },
            '@phpCompileTimeConstants': { token: 'constant.php' },
            '@phpKeywords': { token: 'keyword.php' },
            '@phpFunctions': { token: 'support.function.php' },
            '@default': 'identifier.php',
          },
        },
      ],
      [
        /[$][a-zA-Z_]\w*/,
        {
          cases: {
            '@phpPreDefinedVariables': {
              token: 'variable.predefined.php',
            },
            '@default': 'variable.php',
          },
        },
      ],
      // brackets
      [/[{}]/, 'delimiter.bracket.php'],
      [/[\[\]]/, 'delimiter.array.php'],
      [/[()]/, 'delimiter.parenthesis.php'],
      // whitespace
      [/[ \t\r\n]+/],
      // comments
      [/(#|\/\/)$/, 'comment.php'],
      [/(#|\/\/)/, 'comment.php', '@phpLineComment'],
      // block comments
      [/\/\*/, 'comment.php', '@phpComment'],
      // strings
      [/"/, 'string.php', '@phpDoubleQuoteString'],
      [/'/, 'string.php', '@phpSingleQuoteString'],
      // operators (multi-character first, then single-character)
      [/(===|!==|==|!=|<=|>=|<=>|\+=|\-=|\*=|\/=|\.=|%=|\*\*|\+\+|\-\-|&&|\|\||\?->|->|=>|\?\?|\?:)/, 'operator.php'],
      [/[\=\+\-\*\/\%\.\<\>\!\?\:\&\|\^\~]/, 'operator.php'],
      // delimiters
      [/[\;\,]/, 'delimiter.php'],
      // numbers
      [/\d*\d+[eE]([\-+]?\d+)?/, 'number.float.php'],
      [/\d*\.\d+([eE][\-+]?\d+)?/, 'number.float.php'],
      [/0[xX][0-9a-fA-F']*[0-9a-fA-F]/, 'number.hex.php'],
      [/0[0-7']*[0-7]/, 'number.octal.php'],
      [/0[bB][0-1']*[0-1]/, 'number.binary.php'],
      [/\d[\d']*/, 'number.php'],
      [/\d/, 'number.php'],
    ],
    phpComment: [
      [/\*\//, 'comment.php', '@pop'],
      [/[^*]+/, 'comment.php'],
      [/./, 'comment.php'],
    ],
    phpLineComment: [
      [/\?>/, { token: '@rematch', next: '@pop' }],
      [/.$/, 'comment.php', '@pop'],
      [/[^?]+$/, 'comment.php', '@pop'],
      [/[^?]+/, 'comment.php'],
      [/./, 'comment.php'],
    ],
    phpDoubleQuoteString: [
      // Complex curly variable interpolation: {$var} or {$var->prop} or {$var['key']}
      [/\{(?=\$)/, 'delimiter.bracket.php', '@phpInterpolatedBracketVar'],
      // Direct variable with property: $obj->prop
      [/[$][a-zA-Z_]\w*(?=->)/, 'variable.php', '@phpVarProperty'],
      // Direct variable with array index: $arr[0] or $arr['key']
      [/[$][a-zA-Z_]\w*(?=\[)/, 'variable.php', '@phpVarIndex'],
      // Direct variable interpolation: $var (e.g. $name, $age)
      [/[$][a-zA-Z_]\w*/, 'variable.php'],
      // Escapes: \n, \r, \t, \v, \f, \", \\, \$, etc.
      [/@escapes/, 'string.escape.php'],
      [/\\./, 'string.escape.invalid.php'],
      // Closing quote
      [/"/, 'string.php', '@pop'],
      // Safe string chunk: any sequence of chars except \, ", $, {
      [/[^\\"\$\{]+/, 'string.php'],
      // Fallback for lone $ or lone {
      [/./, 'string.php'],
    ],
    phpInterpolatedBracketVar: [
      [/[$][a-zA-Z_]\w*/, 'variable.php'],
      [/->/, 'operator.php'],
      [/[a-zA-Z_]\w*/, 'identifier.php'],
      [/\[/, 'delimiter.array.php', '@phpVarIndexInsideBracket'],
      [/\}/, 'delimiter.bracket.php', '@pop'],
      [/[ \t\r\n]+/],
      [/./, 'variable.php'],
    ],
    phpVarIndexInsideBracket: [
      [/['"][^'"]*['"]/, 'string.php'],
      [/\d+/, 'number.php'],
      [/[$][a-zA-Z_]\w*/, 'variable.php'],
      [/\]/, 'delimiter.array.php', '@pop'],
      [/./, 'delimiter.array.php'],
    ],
    phpVarProperty: [
      [/->/, 'operator.php'],
      [/[a-zA-Z_]\w*/, 'identifier.php', '@pop'],
      ['', '', '@pop'],
    ],
    phpVarIndex: [
      [/\[/, 'delimiter.array.php'],
      [/['"][^'"]*['"]/, 'string.php'],
      [/\d+/, 'number.php'],
      [/\]/, 'delimiter.array.php', '@pop'],
      ['', '', '@pop'],
    ],
    phpSingleQuoteString: [
      [/[^\\']+/, 'string.php'],
      [/@escapes/, 'string.escape.php'],
      [/\\./, 'string.escape.invalid.php'],
      [/'/, 'string.php', '@pop'],
    ],
  },
  phpConstants: [
    'true',
    'false',
    'null',
    'TRUE',
    'FALSE',
    'NULL',
    'INF',
    'NAN',
    'PHP_VERSION',
    'PHP_MAJOR_VERSION',
    'PHP_MINOR_VERSION',
    'PHP_RELEASE_VERSION',
    'PHP_OS',
    'PHP_EOL',
    'PHP_INT_MAX',
    'PHP_INT_MIN',
  ],
  phpKeywords: [
    'abstract',
    'and',
    'array',
    'as',
    'break',
    'callable',
    'case',
    'catch',
    'cfunction',
    'class',
    'clone',
    'const',
    'continue',
    'declare',
    'default',
    'do',
    'else',
    'elseif',
    'enddeclare',
    'endfor',
    'endforeach',
    'endif',
    'endswitch',
    'endwhile',
    'extends',
    'final',
    'for',
    'foreach',
    'function',
    'global',
    'goto',
    'if',
    'implements',
    'interface',
    'instanceof',
    'insteadof',
    'namespace',
    'new',
    'object',
    'old_function',
    'or',
    'private',
    'protected',
    'public',
    'resource',
    'static',
    'switch',
    'throw',
    'trait',
    'try',
    'use',
    'var',
    'while',
    'xor',
    'die',
    'echo',
    'empty',
    'exit',
    'eval',
    'include',
    'include_once',
    'isset',
    'list',
    'require',
    'require_once',
    'return',
    'print',
    'unset',
    'yield',
    '__construct',
  ],
  phpFunctions: [
    'define',
    'defined',
    'constant',
    'get_defined_constants',
    'var_dump',
    'print_r',
    'printf',
    'sprintf',
    'strlen',
    'count',
    'in_array',
    'array_push',
    'array_pop',
    'array_shift',
    'array_unshift',
    'array_merge',
    'array_keys',
    'array_values',
    'array_slice',
    'array_search',
    'array_key_exists',
    'array_unique',
    'array_flip',
    'array_product',
    'range',
    'sizeof',
    'json_encode',
    'json_decode',
    'str_replace',
    'explode',
    'implode',
    'trim',
    'ltrim',
    'rtrim',
    'strtolower',
    'strtoupper',
    'ucfirst',
    'lcfirst',
    'ucwords',
    'substr',
    'strpos',
    'str_contains',
    'str_starts_with',
    'str_ends_with',
    'is_array',
    'is_string',
    'is_numeric',
    'is_int',
    'is_integer',
    'is_long',
    'is_float',
    'is_double',
    'is_bool',
    'is_null',
    'is_scalar',
    'is_object',
    'is_callable',
    'intval',
    'floatval',
    'strval',
    'boolval',
    'settype',
    'nl2br',
    'addslashes',
    'stripslashes',
    'strcmp',
    'strcasecmp',
    'date',
    'time',
    'strtotime',
    'microtime',
    'rand',
    'mt_rand',
    'random_int',
    'round',
    'floor',
    'ceil',
    'abs',
    'min',
    'max',
    'header',
    'setcookie',
    'session_start',
    'htmlspecialchars',
    'strip_tags',
    'number_format',
    'md5',
    'base64_encode',
    'base64_decode',
    'file_get_contents',
    'file_put_contents',
  ],
  phpCompileTimeConstants: [
    '__CLASS__',
    '__DIR__',
    '__FILE__',
    '__LINE__',
    '__NAMESPACE__',
    '__METHOD__',
    '__FUNCTION__',
    '__TRAIT__',
  ],
  phpPreDefinedVariables: [
    '$GLOBALS',
    '$_SERVER',
    '$_GET',
    '$_POST',
    '$_FILES',
    '$_REQUEST',
    '$_SESSION',
    '$_ENV',
    '$_COOKIE',
    '$php_errormsg',
    '$HTTP_RAW_POST_DATA',
    '$http_response_header',
    '$argc',
    '$argv',
  ],
  escapes: /\\(?:[abefnrtv\\"'\$]|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|[0-7]{1,3})/,
};
